version: 2.1
orbs:
  github-cli: circleci/github-cli@2.2.0
jobs:
  demo1-build:
    working_directory: ~/project/services/demo1
    docker:
      - image: cimg/python:3.11.5
    steps:
      - checkout

  demo1-release-notes:
    working_directory: ~/project/services/demo1
    docker:
      - image: cimg/python:3.11.5
    steps:
      - checkout
      - github-cli/setup
      - run:
          name: Install dependencies
          command: pip install requests
      - run:
          name: Install Python Deps
          command: pip install -r services/demo1/scripts/requirements.txt
      - run:
          name: "Check PR labels"
          command: python services/demo1/scripts/check-pr-labels.py

workflows:
  demo1:
    jobs:
      - demo1-build
      - demo1-release-notes:
          requires:
            - demo1-build
          filters:
            branches:
              only:
                - main