version: 2.1

jobs:
  demo1-build:
    working_directory: ~/project/services/demo1
    docker:
      - image: cimg/python:3.11.5
    steps:
      - checkout

workflows:
  demo1:
    jobs:
      - demo1-build