version: 2.1

jobs:
  demo2-build:
    docker:
      - image: cimg/python:3.11.5
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: cd services/demo2

workflows:
  demo2:
    jobs:
      - demo2-build